---

# Include once to write/set, include a second time to remove/clear

- name: Handle clouds.yaml
  hosts: instances
  connection: local
  vars_files:
    - secret_group_vars/instances.yml
  tasks:
    - name: Set remove_clouds_yaml fact
      set_fact:
        remove_clouds_yaml: "{{ clouds is defined and clouds }}"
    - name: Remove clouds.yaml
      file:
        path: "{{ inventory_dir }}/clouds.yaml"
        state: absent
      when: remove_clouds_yaml
      delegate_to: localhost
      run_once: yes
    - name: Clear clouds fact
      set_fact:
        clouds: null
      when: remove_clouds_yaml
      delegate_to: localhost
    - name: Write clouds.yaml
      copy:
        content: "{{ clouds_yaml | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/clouds.yaml"
        mode: "0400"
      when: not remove_clouds_yaml
      delegate_to: localhost
      run_once: yes
    - name: Set cloud fact
      set_fact:
        clouds: "{{ clouds_yaml.clouds }}"
      when: not remove_clouds_yaml
      delegate_to: localhost
