---

group_packages:
  - git
  # Pulsar deps
  - '@development tools'
  - python-virtualenv
  - libffi-devel
  - libcurl-devel
  - nss-devel
  - openssl-devel
  # FIXME: slurm-drmaa can't be installed on first playbook run because the depot repo is set up by the slurm role
  # - slurm-drmaa

jetstream_scratch0_device: /dev/sdb

directories:
  - path: /jetstream
  - path: /var/lib/slurm
    mode: "0755"
  - path: /srv/pulsar/test
    owner: g2test
    group: G-803372
  - path: /srv/pulsar/test/pulsar/log
    owner: g2test
    group: G-803372
  - path: /srv/pulsar/main
    owner: g2main
    group: G-803372
  - path: /srv/pulsar/main/pulsar/log
    owner: g2main
    group: G-803372

links:
  - path: /jetstream/scratch0
    src: /scratch0
    force: yes

supervisord_install: package
supervisord_group_configs:
  - pulsar
