---

- name: Install virtualenv (yum)
  yum:
    pkg: python-virtualenv
  when: ansible_os_family == "RedHat"

- name: Create virtualenv for elastic components
  pip:
    name: "{{ item }}"
    virtualenv: "/opt/slurm_cloud_provision"
    state: latest
  with_items:
    - setuptools
    - ansible

- name: Copy this playbook
  synchronize:  # sync is much faster than copy but requires chown task below
    src: "{{ playbook_dir }}/../"
    dest: /opt/slurm_cloud_provision/infrastructure-playbook/

- name: Place vault pass
  copy:
    src: "../jetstream_common/files/elasticity/vp"
    dest: /root/.vault-pass
    mode: "0600"

- name: Ensure root's .ssh dir exists
  file:
    path: /root/.ssh
    state: directory

- name: Place PK
  copy:
    src: "../jetstream_common/files/elasticity/elasticity_kp"
    dest: /root/.ssh/id_rsa
    mode: "0600"
