

linuxbrew_user_name: jenkins
linuxbrew_user_home: /var/lib/jenkins
linuxbrew_user_shellrc: "{{ linuxbrew_user_home }}/.bashrc"

linuxbrew_taps:
  - homebrew/science
  - galaxyproject/tap
linuxbrew_recipes:
  - bcftools
  - planemo
  - node

group_packages:
  - openjdk-7-jre-headless
  - ntp
  - ntpdate

# TODO: generate this file automatically from structured data
group_files:
  - src: files/jenkins/jenkins_server_user_ssh_config
    dest: ~jenkins/.ssh/config
    owner: jenkins
    group: jenkins
