---

- name: Generate client key
  command: "openssl genrsa -out {{ docker_ssl_ca_dir }}/key.pem 4096"
  args:
    creates: "{{ docker_ssl_ca_dir }}/key.pem"

- name: Set client key permissions
  file:
    path: "{{ docker_ssl_ca_dir }}/key.pem"
    mode: "0600"

- name: Generate client certificate request
  command: openssl req -subj '/CN={{ inventory_hostname }}' -sha256 -new -key {{ docker_ssl_ca_dir }}/key.pem -out {{ docker_ssl_ca_dir }}/client.csr
  args:
    creates: "{{ docker_ssl_ca_dir }}/client.csr"

- name: Create client extfile
  copy:
    content: "extendedKeyUsage = clientAuth"
    dest: "{{ docker_ssl_ca_dir }}/extfile.cnf"

- include: ssl-ca-passphrase.yml

- name: Sign client certificate request
  command: >
    openssl x509 -req -days 365 -sha256
      -in {{ docker_ssl_ca_dir }}/client.csr
      -CA {{ docker_ssl_ca_dir }}/ca.pem
      -CAkey {{ docker_ssl_ca_dir }}/ca-key.pem
      -CAcreateserial
      -out {{ docker_ssl_ca_dir }}/cert.pem
      -extfile {{ docker_ssl_ca_dir }}/extfile.cnf
      -passin file:{{ docker_ssl_ca_passphrase_file }}
  args:
    creates: "{{ docker_ssl_ca_dir }}/cert.pem"

- include: ssl-ca-passphrase.yml
