---

- name: Create CA directory
  file:
    path: "{{ docker_ssl_ca_dir }}"
    state: directory

- include: ssl-ca-passphrase.yml

- name: Generate CA key
  command: "openssl genrsa -aes256 -out {{ docker_ssl_ca_dir }}/ca-key.pem -passout file:{{ docker_ssl_ca_passphrase_file }} 4096"
  args:
    creates: "{{ docker_ssl_ca_dir }}/ca-key.pem"

- name: Set CA key permissions
  file:
    path: "{{ docker_ssl_ca_dir }}/ca-key.pem"
    mode: "0600"

- name: Generate CA cert
  command: >
    openssl req -new -x509 -days 365 -sha256
      -subj '/C={{ docker_ssl_ca_dn.country }}/ST={{ docker_ssl_ca_dn.state }}/L={{ docker_ssl_ca_dn.locality }}/O={{ docker_ssl_ca_dn.organization }}/OU={{ docker_ssl_ca_dn.organizational_unit }}/CN={{ docker_ssl_ca_dn.common_name }}'
      -key {{ docker_ssl_ca_dir }}/ca-key.pem
      -out {{ docker_ssl_ca_dir }}/ca.pem
      -passin file:{{ docker_ssl_ca_passphrase_file }}
  args:
    creates: "{{ docker_ssl_ca_dir }}/ca.pem"

- include: ssl-ca-passphrase.yml
