---
# Passphrase handling. Writes on include if docker_ssl_ca_passphrase_file is
# unset or null, removes on include if docker_ssl_ca_passphrase_file is set and
# non-null

- name: Remove passphrase tempfile
  file:
    path: "{{ docker_ssl_ca_passphrase_file }}"
    state: absent
  when: docker_ssl_ca_passphrase_file is defined and docker_ssl_ca_passphrase_file

- name: Clear passphrase tempfile fact
  set_fact:
    docker_ssl_ca_passphrase_file: null
  when: docker_ssl_ca_passphrase_file is defined and docker_ssl_ca_passphrase_file

- name: Create passphrase tempfile
  command: mktemp -t tmp.ansible_docker_ssl_XXXXXXXXXX
  register: docker_ssl_mktemp_out
  when: docker_ssl_ca_passphrase_file is undefined or not docker_ssl_ca_passphrase_file

- name: Write passphrase to tempfile
  copy:
    content: "{{ docker_ssl_ca_passphrase }}"
    dest: "{{ docker_ssl_mktemp_out.stdout }}"
    mode: "0600"
  when: docker_ssl_ca_passphrase_file is undefined or not docker_ssl_ca_passphrase_file

- name: Set passphrase tempfile fact
  set_fact:
    docker_ssl_ca_passphrase_file: "{{ docker_ssl_mktemp_out.stdout }}"
  when: docker_ssl_ca_passphrase_file is undefined or not docker_ssl_ca_passphrase_file
