---

- name: Terminate instance(s)
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instance(s)
      os_server:
        cloud: jetstream_iu
        name: "{{ item }}"
        state: absent
      with_items: "{{ jetstream_instances_to_terminate.split(',') }}"
